version: 0.11.7-{build}-{branch}

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

image:
  - Ubuntu1804
  - Ubuntu1604

clone_folder: ~/build/GameHub
clone_depth: 1

environment:
  keys_enc_secret:
    secure: VBUP6GQXENGa7E+H90WDhA==

build_script:
  - sh: bash scripts/build.sh build_deb
  - sh: bash scripts/build.sh build
  - sh: bash scripts/build.sh appimage
  - sh: bash scripts/build.sh appimage_tweak
  - sh: bash scripts/build.sh appimage_bundle_libs
  - sh: bash scripts/build.sh appimage_checkrt
  - sh: bash scripts/build.sh appimage_pack
  - sh: bash scripts/build.sh build_flatpak

install:
  - sh: bash scripts/build.sh import_keys
  - sh: bash scripts/build.sh deps

test: off

artifacts:
  - path: build/*/*.deb
    name: deb
  - path: build/appimage/GameHub*.AppImage*
    name: AppImage
  - path: build/flatpak/GameHub*.flatpak
    name: flatpak

deploy:
  - provider: GitHub
    description: |
        CI build

        * Use `bionic` packages for recent distros (>= Ubuntu 18.04)
        * Use `xenial` packages for older distros (>= Ubuntu 16.04)
    auth_token:
        secure: J2LCcNeVYvzbvHRa/LChp+SmN6UKbg1ELsA4jmxnObCbX+ZyZ9DFH+S2aQIoA3dG
    artifact: deb,AppImage,flatpak
    draft: false
    prerelease: true
